import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


PARAM_COLUMNS = ["tau", "lambda", "clip", "t_apply"]
METRIC_COLUMNS = ["top1", "top10", "tanimoto", "score"]
DISPLAY_LABELS = {
    "tau": r"$\tau$",
    "lambda": r"$\lambda$",
    "t_apply": r"$t_{\mathrm{corr}}$",
    "clip": r"$c_{\mathrm{clip}}$",
    "top1": "Top-1",
    "top10": "Top-10",
    "tanimoto": "Tanimoto",
    "score": "Score",
    "trial": "Trial",
}


def parse_args():
    parser = argparse.ArgumentParser(description="Visualize hyperparameter_search.py results.")
    parser.add_argument(
        "--results-csv",
        default="hyper_search_results.csv",
        help="CSV generated by hyperparameter_search.py.",
    )
    parser.add_argument(
        "--out-dir",
        default="hyperparameter_plots",
        help="Directory for generated figures.",
    )
    parser.add_argument("--dpi", type=int, default=300, help="Figure DPI.")
    parser.add_argument(
        "--smooth-window",
        type=int,
        default=3,
        help="Moving-average window used for smoothed curves.",
    )
    return parser.parse_args()


def setup_matplotlib():
    plt.rcParams["axes.unicode_minus"] = False
    plt.rcParams["figure.facecolor"] = "white"
    plt.rcParams["axes.facecolor"] = "white"
    plt.rcParams["axes.grid"] = True
    plt.rcParams["grid.alpha"] = 0.22
    plt.rcParams["grid.linewidth"] = 0.7
    plt.rcParams["savefig.bbox"] = "tight"
    plt.rcParams["font.size"] = 10
    plt.rcParams["axes.titlesize"] = 11
    plt.rcParams["axes.labelsize"] = 10
    plt.rcParams["legend.fontsize"] = 8.5


def label(name):
    return DISPLAY_LABELS.get(name, name)


def load_results(csv_path):
    csv_path = Path(csv_path).expanduser().resolve()
    if not csv_path.is_file():
        raise FileNotFoundError(f"Cannot find results CSV: {csv_path}")

    df = pd.read_csv(csv_path)
    if df.empty:
        raise ValueError(f"Results CSV is empty: {csv_path}")

    missing = [col for col in PARAM_COLUMNS + ["score"] if col not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in {csv_path}: {missing}")

    for col in PARAM_COLUMNS + METRIC_COLUMNS:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    if "status" not in df.columns:
        df["status"] = "ok"

    df["trial"] = np.arange(1, len(df) + 1)
    return df, csv_path


def save_current(out_dir, name, dpi):
    path = out_dir / name
    plt.savefig(path, dpi=dpi)
    plt.close()
    print(f"Saved: {path}")


def smooth_series(values, window=3):
    series = pd.Series(values, dtype="float64")
    if len(series.dropna()) < 3 or window <= 1:
        return series
    return series.rolling(window=window, center=True, min_periods=1).mean()


def format_axis(ax):
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(axis="both", labelsize=9)


def plot_optimization_trajectory(ax, df, smooth_window=3, show_title=True):
    ok = df[df["score"].notna()].copy()
    if ok.empty:
        return

    best_idx = ok["score"].idxmax()
    best_so_far = ok["score"].cummax()
    smoothed = smooth_series(ok["score"], window=smooth_window)

    ax.plot(
        ok["trial"],
        ok["score"],
        marker="o",
        markersize=4.2,
        linewidth=1.0,
        color="#7fb3d5",
        alpha=0.45,
        label="Raw score",
    )
    ax.plot(
        ok["trial"],
        smoothed,
        linewidth=2.2,
        color="#f97316",
        label="Smoothed score",
    )
    ax.plot(
        ok["trial"],
        best_so_far,
        marker=".",
        markersize=5,
        linewidth=1.9,
        color="#2ca02c",
        label="Best so far",
    )
    ax.scatter(
        df.loc[best_idx, "trial"],
        df.loc[best_idx, "score"],
        s=80,
        color="#d62728",
        edgecolor="white",
        linewidth=0.7,
        zorder=5,
        label="Best",
    )
    ax.set_xlabel(label("trial"))
    ax.set_ylabel(label("score"))
    if show_title:
        ax.set_title("(a) Optimization Trajectory")
    ax.legend(loc="best", frameon=True)
    format_axis(ax)


def normalize_series(series):
    min_v = series.min()
    max_v = series.max()
    if pd.isna(min_v) or pd.isna(max_v) or max_v == min_v:
        return pd.Series(np.full(len(series), 0.5), index=series.index)
    return (series - min_v) / (max_v - min_v)


def plot_metrics_by_trial(ax, df, smooth_window=3, show_title=True):
    metric_specs = [
        ("top1", "Top-1", "#2563eb", "o"),
        ("tanimoto", "Tanimoto", "#dc2626", "s"),
        ("score", "Score", "#7c3aed", "^"),
    ]
    available = [
        spec for spec in metric_specs
        if spec[0] in df.columns and df[spec[0]].notna().any()
    ]
    if not available:
        return

    for col, display_name, color, marker in available:
        ok = df[df[col].notna()].copy()
        normalized = normalize_series(ok[col])
        smoothed = smooth_series(normalized, window=smooth_window)
        ax.plot(
            ok["trial"],
            normalized,
            marker=marker,
            markersize=3.7,
            linewidth=0.85,
            color=color,
            alpha=0.24,
        )
        ax.plot(
            ok["trial"],
            smoothed,
            linewidth=2.0,
            color=color,
            label=display_name,
        )

    ax.set_xlabel(label("trial"))
    ax.set_ylabel("Normalized metric value")
    ax.set_ylim(-0.05, 1.05)
    if show_title:
        ax.set_title("(b) Metrics by Trial")
    ax.legend(loc="best", frameon=True, ncol=1)
    format_axis(ax)


def add_trend_line(ax, x, y):
    if len(x) < 4:
        return
    order = np.argsort(x)
    x_sorted = np.asarray(x)[order]
    y_sorted = np.asarray(y)[order]
    degree = 2 if len(np.unique(x_sorted)) >= 3 else 1
    coeffs = np.polyfit(x_sorted, y_sorted, degree)
    x_grid = np.linspace(x_sorted.min(), x_sorted.max(), 160)
    y_grid = np.polyval(coeffs, x_grid)
    ax.plot(x_grid, y_grid, color="#111827", linewidth=1.5, alpha=0.65, linestyle="--")


def plot_param_sensitivity(ax, df, param, panel_label, smooth=True):
    ok = df[df["score"].notna() & df[param].notna()].copy()
    if ok.empty:
        return

    best_idx = ok["score"].idxmax()
    sc = ax.scatter(
        ok[param],
        ok["score"],
        c=ok["trial"],
        cmap="viridis",
        s=42,
        edgecolor="black",
        linewidth=0.35,
        alpha=0.92,
    )
    if smooth:
        add_trend_line(ax, ok[param].to_numpy(), ok["score"].to_numpy())

    ax.scatter(
        df.loc[best_idx, param],
        df.loc[best_idx, "score"],
        marker="*",
        s=160,
        color="#22c55e",
        edgecolor="black",
        linewidth=0.5,
        zorder=6,
        label="Best",
    )
    ax.set_xlabel(label(param))
    ax.set_ylabel(label("score"))
    ax.set_title(f"({panel_label}) {label(param)} Sensitivity")
    ax.legend(loc="best", frameon=True)
    format_axis(ax)
    return sc


def write_best_summary(df, out_dir, csv_path):
    ok = df[df["score"].notna()].copy()
    if ok.empty:
        return

    best = ok.loc[ok["score"].idxmax()]
    summary_path = out_dir / "best_summary.txt"

    lines = [
        f"Source CSV: {csv_path}",
        f"Trials: {len(df)}",
        "",
        "Best result:",
    ]
    for col in ["trial"] + PARAM_COLUMNS + METRIC_COLUMNS + ["status"]:
        if col in best.index:
            lines.append(f"{col}: {best[col]}")

    summary_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Saved: {summary_path}") 


def plot_individual_figures(df, out_dir, dpi, smooth_window):
    fig, ax = plt.subplots(figsize=(7.0, 4.2))
    plot_optimization_trajectory(ax, df, smooth_window=smooth_window)
    save_current(out_dir, "01_optimization_trajectory.png", dpi)

    fig, ax = plt.subplots(figsize=(7.0, 4.2))
    plot_metrics_by_trial(ax, df, smooth_window=smooth_window)
    save_current(out_dir, "02_metrics_by_trial.png", dpi)

    for idx, (param, name) in enumerate(
        [
            ("tau", "03_tau_sensitivity.png"),
            ("lambda", "04_lambda_sensitivity.png"),
            ("clip", "05_c_sensitivity.png"),
            ("t_apply", "06_tcorr_sensitivity.png"),
        ],
        start=3,
    ):
        fig, ax = plt.subplots(figsize=(5.8, 4.0))
        plot_param_sensitivity(ax, df, param, chr(ord("a") + idx - 1))
        save_current(out_dir, name, dpi)


def plot_combined_figure(df, out_dir, dpi, smooth_window):
    fig, axes = plt.subplots(3, 2, figsize=(12.0, 12.6))

    plot_optimization_trajectory(axes[0, 0], df, smooth_window=smooth_window)
    plot_metrics_by_trial(axes[0, 1], df, smooth_window=smooth_window)
    sc = plot_param_sensitivity(axes[1, 0], df, "tau", "c")
    plot_param_sensitivity(axes[1, 1], df, "lambda", "d")
    plot_param_sensitivity(axes[2, 0], df, "clip", "e")
    plot_param_sensitivity(axes[2, 1], df, "t_apply", "f")

    fig.subplots_adjust(left=0.075, right=0.90, bottom=0.06, top=0.965, hspace=0.52, wspace=0.28)
    if sc is not None:
        cax = fig.add_axes([0.925, 0.18, 0.018, 0.50])
        fig.colorbar(sc, cax=cax, label=label("trial"))

    path = out_dir / "fig2_hyperparameter_analysis.png"
    fig.savefig(path, dpi=dpi)
    plt.close(fig)
    print(f"Saved: {path}")


def main():
    args = parse_args()
    setup_matplotlib()

    df, csv_path = load_results(args.results_csv)
    out_dir = Path(args.out_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    plot_combined_figure(df, out_dir, args.dpi, args.smooth_window)
    plot_individual_figures(df, out_dir, args.dpi, args.smooth_window)
    write_best_summary(df, out_dir, csv_path)

    print()
    print(f"Done. Figures are in: {out_dir}")


if __name__ == "__main__":
    main()
